#! /bin/sh

killall pasystray;pasystray &
killall sxhkd;sxhkd &
# killall tundra;tundra daemon &
killall flameshot;flameshot &
# solaar --window=hide &
~/.config/polybar/launch.sh

# Make Java behave
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           8
bspc config top_padding          8

bspc config active_border_color	"#2E3440"
# bspc config active_border_color	"#BF616A"
# bspc config focused_border_color "#5E81AC"
bspc config focused_border_color "#BF616A"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a '*:*:Picture-in-picture' state=floating

$HOME/.config/bspwm/autostart.sh &
