lastupdatecheck: 0
recentrepos:
- /home/aditeya/Documents/krishikan/web
- /home/aditeya/code/1.projects/maus_raytracing_in_one_weekend
- /home/aditeya/Documents/krishikan/server
- /home/aditeya/code/1.projects/lists
- /home/aditeya/code/1.projects/hopalong-redux
- /home/aditeya/code/1.projects/maus_project_euler
- /home/aditeya/code/1.projects/LeWorldAfter.github.io
- /home/aditeya/code/1.projects/aditeya.github.io
- /home/aditeya/code/1.projects/maus_mental_maths
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
